import type { ApUnit } from "./types";

function U(prefix: string, titles: string[]): ApUnit[] {
  return titles.map((title, i) => ({
    id: `${prefix}-u${i + 1}`,
    index: i + 1,
    title,
    summary: `Practice for Unit ${i + 1}: ${title}.`,
  }));
}

/** Canonical units per course id (aligned with typical CB syllabi; titles may vary slightly by year). */
export const AP_UNITS_BY_COURSE_ID: Record<string, ApUnit[]> = {
  "calc-ab": U("calc-ab", [
    "Limits and Continuity",
    "Differentiation: Definition and Fundamental Properties",
    "Differentiation: Composite, Implicit, and Inverse Functions",
    "Contextual Applications of Differentiation",
    "Analytical Applications of Differentiation",
    "Integration and Accumulation of Change",
    "Differential Equations",
    "Applications of Integration",
  ]),
  "calc-bc": U("calc-bc", [
    "Limits and Continuity",
    "Differentiation: Definition and Fundamental Properties",
    "Differentiation: Composite, Implicit, and Inverse Functions",
    "Contextual Applications of Differentiation",
    "Analytical Applications of Differentiation",
    "Integration and Accumulation of Change",
    "Differential Equations",
    "Applications of Integration",
    "Parametric Equations, Polar Coordinates, and Vector-Valued Functions",
    "Infinite Sequences and Series",
  ]),
  precalc: U("precalc", [
    "Polynomial and Rational Functions",
    "Exponential and Logarithmic Functions",
    "Trigonometric and Polar Functions",
    "Functions Involving Parameters, Vectors, and Matrices",
    "Conics and Advanced Graphing",
    "Sequences, Series, and Mathematical Induction",
    "Limits and Introductory Calculus Ideas",
    "Modeling with Functions and Data",
  ]),
  stats: U("stats", [
    "Exploring One-Variable Data",
    "Exploring Two-Variable Data",
    "Collecting Data",
    "Probability, Random Variables, and Probability Distributions",
    "Sampling Distributions",
    "Inference for Categorical Data: Proportions",
    "Inference for Quantitative Data: Means",
    "Inference for Categorical Data: Chi-Square",
    "Inference for Quantitative Data: Slopes",
  ]),
  "cs-a": U("cs-a", [
    "Primitive Types and Using Objects",
    "Boolean Expressions and if Statements",
    "While Loops, String Traversal, and Algorithms",
    "Array Traversal and Algorithms",
    "Writing Classes",
    "ArrayList and Searching/Sorting",
    "Inheritance and Polymorphism",
    "Recursion",
  ]),
  csp: U("csp", [
    "Creative Development",
    "Data",
    "Algorithms and Programming",
    "Computing Systems and Networks",
    "Impact of Computing",
    "Investigative Practices",
  ]),
  "physics-1": U("physics-1", [
    "Kinematics",
    "Dynamics",
    "Circular Motion and Gravitation",
    "Energy",
    "Momentum",
    "Simple Harmonic Motion",
    "Torque and Rotational Motion",
    "Electric Charge and Electric Force",
    "DC Circuits",
    "Mechanical Waves and Sound",
  ]),
  "physics-2": U("physics-2", [
    "Fluids",
    "Thermodynamics",
    "Electric Force, Field, and Potential",
    "Electric Circuits",
    "Magnetism and Electromagnetic Induction",
    "Geometric and Physical Optics",
    "Quantum, Atomic, and Nuclear Physics",
  ]),
  "physics-c-m": U("physics-c-m", [
    "Kinematics",
    "Newton’s Laws of Motion",
    "Work, Energy, and Power",
    "Systems of Particles and Linear Momentum",
    "Rotation",
    "Oscillations",
    "Gravitation",
  ]),
  "physics-c-em": U("physics-c-em", [
    "Electrostatics",
    "Conductors, Capacitors, and Dielectrics",
    "Electric Circuits",
    "Magnetic Fields",
    "Electromagnetism",
    "Optics (Physical)",
  ]),
  chem: U("chem", [
    "Atomic Structure and Properties",
    "Molecular and Ionic Compound Structure and Properties",
    "Intermolecular Forces and Properties",
    "Chemical Reactions",
    "Kinetics",
    "Thermodynamics",
    "Equilibrium",
    "Acids and Bases",
    "Applications of Thermodynamics",
  ]),
  bio: U("bio", [
    "Chemistry of Life",
    "Cell Structure and Function",
    "Cellular Energetics",
    "Cell Communication and Cell Cycle",
    "Heredity",
    "Gene Expression and Regulation",
    "Natural Selection",
    "Ecology",
  ]),
  env: U("env", [
    "The Living World: Ecosystems",
    "The Living World: Biodiversity",
    "Populations",
    "Earth Systems and Resources",
    "Land and Water Use",
    "Energy Resources and Consumption",
    "Atmospheric Pollution",
    "Aquatic and Terrestrial Pollution",
    "Global Change",
  ]),
  ush: U("ush", [
    "Period 1: 1491–1607",
    "Period 2: 1607–1754",
    "Period 3: 1754–1800",
    "Period 4: 1800–1848",
    "Period 5: 1844–1877",
    "Period 6: 1865–1898",
    "Period 7: 1890–1945",
    "Period 8: 1945–1980",
    "Period 9: 1980–Present",
  ]),
  wh: [
    {
      id: "wh-u1",
      index: 1,
      title: "The Global Tapestry",
      summary:
        "States and belief systems c. 1200: post-classical developments, major world religions (Buddhism, Christianity, Confucianism, Hinduism, Islam, Judaism), regional powers (Abbasid, Song, feudal Europe, Japan, Delhi Sultanate, Khmer, Mesoamerican empires), trade and social structures.",
    },
    {
      id: "wh-u2",
      index: 2,
      title: "Networks of Exchange",
      summary:
        "Hanseatic League, Crusades, scholasticism and universities, Mongol expansion, Mali and Songhai, Indian Ocean and Silk Road trade, Black Death, travelers (Ibn Battuta, Marco Polo), urbanization and cultural diffusion 1200–1450.",
    },
    {
      id: "wh-u3",
      index: 3,
      title: "Land-Based Empires",
      summary:
        "Renaissance humanism, Reformation and Catholic Reformation, Scientific Revolution, gunpowder empires (Ottoman, Safavid, Mughal), European state-building, Qing and Tokugawa, Atlantic slavery and resistance in Africa and the Americas.",
    },
    {
      id: "wh-u4",
      index: 4,
      title: "Transoceanic Interconnections",
      summary:
        "Iberian exploration, Treaty of Tordesillas, Columbian Exchange, encomienda, African slave trade and Middle Passage, mercantilism and joint-stock companies, silver and global trade, colonial societies 1450–1750.",
    },
    {
      id: "wh-u5",
      index: 5,
      title: "Revolutions",
      summary:
        "Enlightenment and Atlantic revolutions (US, France, Haiti, Latin America), industrial beginnings, nationalism, socialism/Marxism, women’s rights debates, resistance to early industrialization.",
    },
    {
      id: "wh-u6",
      index: 6,
      title: "Consequences of Industrialization",
      summary:
        "Imperialism and ideologies of rule, British India, unequal treaties and Meiji Japan, scramble for Africa and Berlin Conference, labor and reform, economic dependency and environmental extraction.",
    },
    {
      id: "wh-u7",
      index: 7,
      title: "Global Conflict",
      summary:
        "World War I and Versailles, Russian Revolution, interwar crises and fascism, World War II and Holocaust, UN and new international order.",
    },
    {
      id: "wh-u8",
      index: 8,
      title: "Cold War and Decolonization",
      summary:
        "Containment, NATO/Warsaw Pact, decolonization (South Asia, Africa, Middle East), China’s civil war, Korea and Vietnam, Cuban Missile Crisis, Non-Aligned Movement, end of the USSR.",
    },
    {
      id: "wh-u9",
      index: 9,
      title: "Globalization",
      summary:
        "Institutions (WTO, UN, ICC), regional trade, terrorism and conflict after 9/11, China and India in the world economy, migration, global health, environment, internet and culture.",
    },
  ],
  euro: U("euro", [
    "Renaissance and Exploration",
    "Age of Reformation",
    "Absolutism and Constitutionalism",
    "Scientific, Philosophical, and Political Developments",
    "Conflict, Crisis, and Reaction in the Late 18th Century",
    "Industrialization and Its Effects",
    "19th-Century Perspectives and Political Developments",
    "20th-Century Global Conflicts",
    "Cold War and Contemporary Europe",
  ]),
  gov: U("gov", [
    "Foundations of American Democracy",
    "Interactions Among Branches of Government",
    "Civil Liberties and Civil Rights",
    "American Political Ideologies and Beliefs",
    "Political Participation",
  ]),
  "comp-gov": U("comp-gov", [
    "Introduction to Comparative Politics",
    "Sovereignty, Authority, and Power",
    "Political Institutions",
    "Citizens, Society, and the State",
    "Political and Economic Change",
    "Public Policy",
  ]),
  macro: U("macro", [
    "Basic Economic Concepts",
    "Economic Indicators and the Business Cycle",
    "National Income and Price Determination",
    "The Financial Sector",
    "Long-Run Consequences of Stabilization Policies",
    "Open Economy: International Trade and Finance",
  ]),
  micro: U("micro", [
    "Basic Economic Concepts",
    "Supply and Demand",
    "Production, Cost, and the Perfect Competition Model",
    "Imperfect Competition",
    "Factor Markets",
    "Market Failure and the Role of Government",
  ]),
  psych: U("psych", [
    "Scientific Foundations of Psychology",
    "Biological Bases of Behavior",
    "Sensation and Perception",
    "Learning",
    "Cognitive Psychology",
    "Developmental Psychology",
    "Motivation, Emotion, and Personality",
    "Clinical Psychology",
    "Social Psychology",
  ]),
  "hum-geo": U("hum-geo", [
    "Thinking Geographically",
    "Population and Migration Patterns and Processes",
    "Cultural Patterns and Processes",
    "Political Patterns and Processes",
    "Agriculture and Rural Land-Use Patterns",
    "Cities and Urban Land-Use Patterns",
    "Industrial and Economic Development Patterns",
  ]),
  lang: U("lang", [
    "Rhetorical Situation",
    "Claims and Evidence",
    "Reasoning and Organization",
    "Style",
    "Reading Arguments",
    "Writing Arguments",
    "Research and Synthesis",
    "Revision and Reflection",
  ]),
  lit: U("lit", [
    "Short Fiction",
    "Poetry",
    "Longer Fiction or Drama",
    "Literary Argument",
    "Reading Complex Texts",
    "Figurative Language and Structure",
    "Characterization and Setting",
    "Themes Across Texts",
  ]),
  "art-hist": U("art-hist", [
    "Global Prehistory",
    "The Ancient Mediterranean",
    "Early Europe and Colonial Americas",
    "Later Europe and Americas",
    "Indigenous Americas",
    "Africa",
    "West and Central Asia",
    "South, East, and Southeast Asia",
    "The Pacific",
    "Global Contemporary",
  ]),
  "art-design": U("art-design", [
    "Inquiry and Investigation",
    "Making and Practice",
    "Experimentation and Revision",
    "Communication and Presentation",
    "Sustained Investigation Documentation",
    "Selected Works",
    "Reflection and Critique",
    "Connecting to Context",
  ]),
  music: U("music", [
    "Fundamentals: Pitch and Rhythm",
    "Scales, Keys, and Modes",
    "Harmony and Voice Leading",
    "Chord Function and Progressions",
    "Melodic Organization",
    "Texture and Form",
    "Aural Skills: Dictation",
    "Aural Skills: Sight-singing",
  ]),
  spanish: U("spanish", [
    "Families and Communities",
    "Personal and Public Identities",
    "Beauty and Aesthetics",
    "Science and Technology",
    "Contemporary Life",
    "Global Challenges",
    "Interpretive Communication",
    "Interpersonal Communication",
    "Presentational Communication",
  ]),
  french: U("french", [
    "Families and Communities",
    "Personal and Public Identities",
    "Beauty and Aesthetics",
    "Science and Technology",
    "Contemporary Life",
    "Global Challenges",
    "Interpretive Communication",
    "Interpersonal Communication",
    "Presentational Communication",
  ]),
  german: U("german", [
    "Families and Communities",
    "Personal and Public Identities",
    "Beauty and Aesthetics",
    "Science and Technology",
    "Contemporary Life",
    "Global Challenges",
    "Interpretive Communication",
    "Interpersonal Communication",
    "Presentational Communication",
  ]),
  latin: U("latin", [
    "Reading and Comprehension",
    "Grammar and Syntax",
    "Figures of Speech and Style",
    "Culture and Context",
    "Sight Reading",
    "Meter and Scansion",
    "Essay and Analysis",
    "Vergil and Caesar Skills",
  ]),
  chinese: U("chinese", [
    "Families and Communities",
    "Personal and Public Identities",
    "Beauty and Aesthetics",
    "Science and Technology",
    "Contemporary Life",
    "Global Challenges",
    "Interpretive Communication",
    "Interpersonal Communication",
    "Presentational Communication",
  ]),
  japanese: U("japanese", [
    "Families and Communities",
    "Personal and Public Identities",
    "Beauty and Aesthetics",
    "Science and Technology",
    "Contemporary Life",
    "Global Challenges",
    "Interpretive Communication",
    "Interpersonal Communication",
    "Presentational Communication",
  ]),
  seminar: U("seminar", [
    "Question and Explore",
    "Understand and Analyze",
    "Evaluate Multiple Perspectives",
    "Synthesize Ideas",
    "Teamwork and Collaboration",
    "Individual Research",
    "Presentation and Defense",
    "Reflection",
  ]),
  research: U("research", [
    "Topic Exploration",
    "Preliminary Research",
    "Literature Review",
    "Methodology Design",
    "Data Collection",
    "Analysis and Interpretation",
    "Writing the Academic Paper",
    "Presentation and Defense",
  ]),
};
